<?php

namespace ContainerMpX7iTK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Errored__LqQ26WService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..lqQ26W' shared service.
     *
     * @return \App\Symfony\Component\Security\Core\Encoder\UserPasswordEncoderInterface
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot determine controller argument for "App\\Controller\\ResetPasswordController::update()": the $encoder argument is type-hinted with the non-existent class or interface: "App\\Symfony\\Component\\Security\\Core\\Encoder\\UserPasswordEncoderInterface".');
    }
}
