<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUvbUvy4\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUvbUvy4/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerUvbUvy4.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerUvbUvy4\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerUvbUvy4\App_KernelDevDebugContainer([
    'container.build_hash' => 'UvbUvy4',
    'container.build_id' => '5ea0f7d5',
    'container.build_time' => 1643578423,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerUvbUvy4');
